### ISSUE TITLE
Creating index using php artisan not working

### ISSUE THREAD

**Issue by mikhi** [shokme/laravel-scout-meilisearch#115] opened 2021-03-16 09:46 UTC
Hi Guys,

Great package so far. I have a small issue: I cannot create an index using artisan command.

I get this error for:  `php artisan scout:index myindexname`
Argument 1 passed to MeiliSearch\Client::__construct() must be of the type string, null given....

I'm using:
Laravel 8
PHP 7.4

Any help would be appreciated!
Thanks,
Mihai

**Comment by mmachatschek** [comment] 2021-03-16 10:11
Hi @mikhi,

it looks like you didn't setup the `meilisearch.host` config under `config/meilisearch.php`.

Did you run both commands from the [install instructions](https://github.com/meilisearch/meilisearch-laravel-scout#export-configuration-)?

**Comment by mikhi** [comment] 2021-03-16 10:30
Hi @mmachatschek 

I followed the instructions. 
The MEILISEARCH_HOST  & MEILISEARCH_KEY are set.

Basically any scout command is not working.
![image](https://user-images.githubusercontent.com/1406293/111294553-1fde4500-8653-11eb-9d87-2c61d91fc160.png)

The composer.json file looks like this:
![image](https://user-images.githubusercontent.com/1406293/111294717-47cda880-8653-11eb-89fa-fcc8a00b5064.png)

I'm missing something?

**Comment by mmachatschek** [comment] 2021-03-16 10:35
@mikhi ahh I see where the problem is. It looks like you are using the algolia driver of scout. 

This should be fixed by setting the SCOUT_DRIVER environment variable. [See the link](https://github.com/meilisearch/meilisearch-laravel-scout#update-the-env-file-)

**Comment by mikhi** [comment] 2021-03-16 10:39
I already do that...

in .env file
![image](https://user-images.githubusercontent.com/1406293/111295780-713b0400-8654-11eb-9edb-902724411386.png)

and in scout.php config file
![image](https://user-images.githubusercontent.com/1406293/111295904-93cd1d00-8654-11eb-8371-d924c9508c1d.png)


Somehow remains related with algolia driver and not meili

**Comment by mmachatschek** [comment] 2021-03-16 10:43
@mikhi then the only option there could be is that you have config caching active.

Can you try running `php artisan config:clear` if this solves the issue?

**Comment by mikhi** [comment] 2021-03-16 10:46
@mmachatschek yes, that was the case. Stupid me..
Thanks allot for your help!

**Comment by mmachatschek** [comment] 2021-03-16 10:47
@mikhi happens to the best! Hope you have fun setting everything up :grin:

**Closed as completed by mmachatschek** 2021-03-16 10:47 UTC
